version: 2.1
commands:
  run-npm-test:
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn test
      - store_artifacts:
          path: build
      - run:
          command: |
            curl -X POST -v -H "Content-type: application/json" \
            --data '{"text": "DEPLOY DONE! <<pipeline.project.git_url>>"}' \
            ${SLACK_NOTICE_HOOK}

jobs:
  # MEMO: jobが一つの場合は、job名は「build」でなければならない
  build:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  version: 2
  test_workflow:
    jobs:
      - build